spring:
  main:
    banner-mode: off

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/dm"
    username: "user"
    password: "password"

  sql:
    init:
      mode: always

server:
  port: 8081
  servlet:
    context-path: "/api"

pattern:
  phones:
    - "^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$"
    - "((^\\d{4,10})|(\\s\\(\\d{3}\\)\\s\\d{3}\\s\\d{2}\\s\\d{2}))"
  emails:
    - "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$"
  date: "dd.MM.yyyy"
  date-time: "dd.MM.yyyy HH:mm:ss"

cache:
  entries: 5000
  heap-size: 5
  duration: 3600
  values:
    - "accounts"
    - "contacts"
    - "people"

kafka:
  bootstrap-servers:
    - "localhost:9092"
  topics:
    dm-log:
      partitions: 1
      replicas: 1

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    ru.smaginv.debtmanager.dm: debug
    org.springframework.cache: trace
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"